# Generated by Django 3.0.7 on 2020-07-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointclouds', '0002_potreevisualization_navbar_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='potreevisualization',
            name='copyright_notice',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='potreevisualization',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='potreevisualization',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
    ]
