# Generated by Django 3.0.7 on 2020-08-03 07:16

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pointclouds', '0005_auto_20200702_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotreeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('position', models.CharField(help_text='x,y,z using comma separated values', max_length=254)),
                ('camera_position', models.CharField(blank=True, help_text='x,y,z using comma separated values', max_length=254)),
                ('camera_target', models.CharField(blank=True, help_text='x,y,z using comma separated values', max_length=254)),
                ('order', models.PositiveIntegerField(default=0)),
                ('img', models.ImageField(upload_to='galleries')),
                ('pointcloud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pointclouds.PotreeModel')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='PotreeAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('position', models.CharField(help_text='x,y,z using comma separated values', max_length=254)),
                ('camera_position', models.CharField(blank=True, help_text='x,y,z using comma separated values', max_length=254)),
                ('camera_target', models.CharField(blank=True, help_text='x,y,z using comma separated values', max_length=254)),
                ('order', models.PositiveIntegerField(default=0)),
                ('body', ckeditor.fields.RichTextField(blank=True)),
                ('pointcloud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pointclouds.PotreeModel')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
