# Generated by Django 3.0.7 on 2020-08-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointclouds', '0007_auto_20200803_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='potreeannotation',
            name='position',
            field=models.CharField(blank=True, help_text='x,y,z using comma separated values', max_length=254),
        ),
    ]
