# Generated by Django 3.0.7 on 2020-10-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointclouds', '0008_potreeannotation_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='potreevisualization',
            name='show_gallery',
            field=models.BooleanField(default=True),
        ),
    ]
