# Generated by Django 3.1.3 on 2021-04-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointclouds', '0011_auto_20210408_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualization',
            name='potree_config',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
