# Generated by Django 3.1.3 on 2021-05-31 09:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pointclouds', '0012_auto_20210408_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Identifier for the model', max_length=254)),
                ('order', models.PositiveIntegerField(default=0)),
                ('img', models.ImageField(upload_to='galleries')),
                ('visualization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='pointclouds.visualization')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
