# Generated by Django 3.1.3 on 2021-06-12 02:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pointclouds', '0013_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UndergroundDepiction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Identifier for the depiction', max_length=254)),
                ('img', models.ImageField(upload_to='underground')),
                ('visualization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='underground_depictions', to='pointclouds.visualization')),
            ],
        ),
    ]
