# Generated by Django 3.1.13 on 2021-11-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointclouds', '0014_undergrounddepiction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='undergrounddepiction',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Georeferenced images'},
        ),
        migrations.AddField(
            model_name='visualization',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
