# Generated by Django 3.0.7 on 2020-07-02 08:07

import colorfield.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collaborators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotreeModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Identifier for the model - Internal Use', max_length=254)),
                ('pointcloud_url', models.CharField(help_text='Full url for accessing the root folder of the point cloud cloud.js', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PotreeVisualization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Viewer Title', max_length=254)),
                ('subtitle', models.CharField(blank=True, help_text='Viewer Title', max_length=254)),
                ('tools_enabled', models.BooleanField(default=True)),
                ('initial_point_size', models.FloatField(blank=True, null=True)),
                ('initial_fov', models.FloatField(blank=True, null=True)),
                ('initial_opacity', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=1)])),
                ('initial_edl_enabled', models.BooleanField(default=True)),
                ('initial_edl_radius', models.FloatField(blank=True, null=True)),
                ('initial_edl_strength', models.FloatField(blank=True, null=True)),
                ('initial_point_budget', models.FloatField(blank=True, null=True)),
                ('initial_show_bounding_box', models.BooleanField(default=False)),
                ('initial_material', models.CharField(blank=True, max_length=254)),
                ('initial_point_sizing', models.CharField(blank=True, max_length=254)),
                ('initial_quality', models.CharField(blank=True, max_length=254)),
                ('initial_position', models.CharField(blank=True, max_length=254)),
                ('initial_target', models.CharField(blank=True, max_length=254)),
                ('initial_background', models.CharField(blank=True, choices=[('', 'None'), ('skybox', 'Skybox'), ('gradient', 'Gradient'), ('black', 'Black'), ('white', 'White')], default='', max_length=254)),
                ('show_appearance', models.BooleanField(default=True)),
                ('show_tools', models.BooleanField(default=True)),
                ('show_scene', models.BooleanField(default=True)),
                ('show_filters', models.BooleanField(default=True)),
                ('show_about', models.BooleanField(default=True)),
                ('background_color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='PotreeVisualizationCollaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=9)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaborators.Collaborator')),
                ('visualization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pointclouds.PotreeVisualization')),
            ],
        ),
        migrations.AddField(
            model_name='potreevisualization',
            name='collaborators',
            field=models.ManyToManyField(through='pointclouds.PotreeVisualizationCollaborator', to='collaborators.Collaborator'),
        ),
        migrations.AddField(
            model_name='potreevisualization',
            name='pointclouds',
            field=models.ManyToManyField(blank=True, to='pointclouds.PotreeModel'),
        ),
    ]
