# Generated by Django 3.0.7 on 2020-07-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointclouds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='potreevisualization',
            name='navbar_height',
            field=models.PositiveSmallIntegerField(default=80, help_text='Navbar height in pixels'),
        ),
    ]
