# Generated by Django 3.0.7 on 2020-07-02 09:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointclouds', '0003_auto_20200702_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potreevisualization',
            name='copyright_notice',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
