# Generated by Django 3.0.7 on 2020-07-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointclouds', '0004_auto_20200702_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='potreevisualization',
            name='initial_point_size',
        ),
        migrations.AddField(
            model_name='potreemodel',
            name='material_point_size_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Fixed'), (1, 'Attenuated'), (2, 'Adaptive')], default=2),
        ),
        migrations.AddField(
            model_name='potreemodel',
            name='material_shape',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Square'), (1, 'Circle'), (2, 'Paraboloid')], default=1),
        ),
    ]
