# Generated by Django 3.0.7 on 2020-08-03 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pointclouds', '0006_potreeannotation_potreeimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='potreeannotation',
            name='position',
        ),
        migrations.RemoveField(
            model_name='potreeimage',
            name='position',
        ),
        migrations.AlterField(
            model_name='potreeannotation',
            name='pointcloud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='pointclouds.PotreeModel'),
        ),
        migrations.AlterField(
            model_name='potreeimage',
            name='pointcloud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pointclouds.PotreeModel'),
        ),
    ]
